services:
  firestore-emulator:
    build:
      context: .
      dockerfile: Dockerfile.firestore-emulator
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "bash", "-lc", "nc -z localhost 8080"]
      interval: 2s
      timeout: 2s
      retries: 30

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      FIRESTORE_EMULATOR_HOST: firestore-emulator:8080
    depends_on:
      firestore-emulator:
        condition: service_healthy
    ports:
      - "8080:8080"
